# Site settings
title: Vyno Agency
email: contact@vynoagency.work
description: > # this means "folded" — all lines until next key are joined into one
  Player representation and scouting with a data-driven approach. 
  Bridging South American talent with Asian football markets.
baseurl: "" # leave empty if site is at root, e.g. username.github.io
url: "https://vynoagency.github.io" # or your custom domain later

instagram_username: vyno.agency

email: contact@vynoagency.work

# Build settings
markdown: kramdown
